name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 更新到 v4 版本，避免 v3 过期问题

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # 解决之前 v3 过期的问题
        with:
          name: github-pages
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # 旧版 v1 被废弃，需更新
